export const sessions = [
  {
    id: 1,
    title: "Italian Night",
    host: "Chef Mario",
    participants: 12,
    startTime: "19:00",
  },
  {
    id: 2,
    title: "Vegan Delights",
    host: "Chef Lisa",
    participants: 8,
    startTime: "20:00",
  },
  {
    id: 3,
    title: "Sushi Making",
    host: "Chef Sato",
    participants: 10,
    startTime: "18:00",
  },
  {
    id: 4,
    title: "French Cuisine",
    host: "Chef Pierre",
    participants: 15,
    startTime: "21:00",
  },
  {
    id: 5,
    title: "Mexican Fiesta",
    host: "Chef Elena",
    participants: 9,
    startTime: "17:00",
  },
  {
    id: 6,
    title: "BBQ Masterclass",
    host: "Chef John",
    participants: 14,
    startTime: "16:00",
  },
  {
    id: 7,
    title: "Pastry Perfection",
    host: "Chef Marie",
    participants: 7,
    startTime: "14:00",
  },
  {
    id: 8,
    title: "Indian Spices",
    host: "Chef Anil",
    participants: 11,
    startTime: "13:00",
  },
  {
    id: 9,
    title: "Seafood Special",
    host: "Chef Alice",
    participants: 13,
    startTime: "15:00",
  },
  {
    id: 10,
    title: "Breakfast Bonanza",
    host: "Chef Karen",
    participants: 6,
    startTime: "09:00",
  },
];
